
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
              "on-error-container": "#6e0a12",
              "surface-container-high": "#e6e9e9",
              "primary-fixed-dim": "#65a4ea",
              "on-surface-variant": "#5b6061",
              "error-container": "#fa746f",
              "secondary-container": "#ffdea5",
              "tertiary-container": "#fb6e6d",
              "secondary-fixed": "#ffdea5",
              "secondary": "#7c5900",
              "error-dim": "#67040d",
              "on-secondary-fixed-variant": "#775600",
              "surface-variant": "#dfe3e4",
              "on-secondary-fixed": "#543b00",
              "inverse-on-surface": "#9c9d9d",
              "tertiary-dim": "#9b272c",
              "primary-dim": "#005592",
              "on-primary-container": "#003055",
              "outline-variant": "#afb3b3",
              "on-surface": "#2f3334",
              "on-tertiary-container": "#440006",
              "surface-tint": "#0d62a3",
              "surface-bright": "#f9f9f9",
              "surface-dim": "#d7dbdb",
              "inverse-primary": "#73b2f9",
              "outline": "#777b7c",
              "on-secondary-container": "#6b4c00",
              "on-tertiary": "#fff7f6",
              "on-tertiary-fixed-variant": "#57000b",
              "error": "#a83836",
              "on-tertiary-fixed": "#000000",
              "on-secondary": "#fff8f1",
              "primary-fixed": "#73b2f9",
              "on-background": "#2f3334",
              "inverse-surface": "#0c0f0f",
              "secondary-dim": "#6d4e00",
              "on-primary": "#f7f9ff",
              "surface": "#f9f9f9",
              "tertiary": "#ac3437",
              "surface-container-highest": "#dfe3e4",
              "secondary-fixed-dim": "#ffcd6b",
              "on-primary-fixed-variant": "#003964",
              "on-primary-fixed": "#00152b",
              "on-error": "#fff7f6",
              "surface-container-lowest": "#ffffff",
              "primary-container": "#73b2f9",
              "background": "#f9f9f9",
              "surface-container": "#eceeee",
              "primary": "#0d62a3",
              "surface-container-low": "#f2f4f4",
              "tertiary-fixed": "#fb6e6d",
              "tertiary-fixed-dim": "#ea6261"
            },
            fontFamily: {
              "headline": ["Lexend"],
              "body": ["Lexend"],
              "label": ["Lexend"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
          },
        },
      };
